# Generated by Django 5.2.4 on 2025-08-01 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="item_photos/"),
                ),
                ("brand", models.CharField(blank=True, max_length=50)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("long_description", models.TextField(blank=True)),
                ("short_description", models.CharField(blank=True, max_length=255)),
                ("compatible_models", models.CharField(blank=True, max_length=255)),
                ("similar_items", models.CharField(blank=True, max_length=255)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("origin", models.CharField(blank=True, max_length=100)),
                ("weight", models.FloatField(blank=True, null=True)),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[
                            ("PC", "Peça"),
                            ("BOX", "Caixa"),
                            ("PAIR", "Par"),
                            ("KIT", "Kit"),
                        ],
                        default="PC",
                        max_length=4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
