# Generated by Django 4.2.23 on 2025-08-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_supplier_cnpj"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="cnpj_validation_overridden",
            field=models.BooleanField(
                default=False, verbose_name="Validação de CNPJ forçada"
            ),
        ),
    ]
