# Generated by Django 4.2.23 on 2025-08-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_populate_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="ean",
            field=models.CharField(
                blank=True,
                help_text="Código de barras EAN-13 (12 ou 13 dígitos)",
                max_length=13,
                null=True,
                unique=True,
                verbose_name="EAN",
            ),
        ),
    ]
