# Generated by Django 4.2.23 on 2025-08-27 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_supplier_cnpj_validation_overridden"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                verbose_name="Foto de Perfil",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_items_per_page",
            field=models.PositiveIntegerField(
                default=25,
                validators=[django.core.validators.MinValueValidator(10)],
                verbose_name="Itens por Página (Padrão)",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorited_items",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorited_by",
                to="inventory.item",
                verbose_name="Itens Favoritos",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorited_suppliers",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorited_by",
                to="inventory.supplier",
                verbose_name="Fornecedores Favoritos",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_theme",
            field=models.CharField(
                choices=[
                    ("SYSTEM", "Padrão do Sistema"),
                    ("LIGHT", "Claro"),
                    ("DARK", "Escuro"),
                ],
                default="SYSTEM",
                max_length=10,
                verbose_name="Tema Preferido",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="table_density",
            field=models.CharField(
                choices=[("COMFORTABLE", "Confortável"), ("COMPACT", "Compacto")],
                default="COMFORTABLE",
                max_length=12,
                verbose_name="Densidade da Tabela",
            ),
        ),
    ]
